### PR TITLE
fix crash on tooltip close

### PR DESCRIPTION
**Pull request by gamesminer**
Application crashes when user close the tooltip before 300ms timeout expiration

### CODE REVIEW

**Comment by VadyaZombie** [comment]
I have been waiting for this fix for a very long time, thanks <3

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/92

**Comment by v-rudkovskiy** [comment]
PR: https://github.com/Labs64/GuideChimp/pull/92

**Comment by r-brown** [comment]
fix included in release [3.2.2](https://github.com/Labs64/GuideChimp/releases/tag/3.2.2)

**Pull request closed without merging**
